/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * slopornot
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { api } from '../lib/api';
export type GetSetsDate200ImagesItem = {
  id: string;
  set_id: string;
  storage_url: string;
  is_ai: boolean;
  created_at: unknown;
};

export type GetSetsDate200 = {
  id: string;
  date: string;
  created_at: unknown;
  images: GetSetsDate200ImagesItem[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getSetsDate = (
    date: string,
 options?: SecondParameter<typeof api>,signal?: AbortSignal
) => {
      
      
      return api<GetSetsDate200>(
      {url: `/sets/${date}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSetsDateQueryKey = (date?: string,) => {
    return [
    `/sets/${date}`
    ] as const;
    }

    
export const getGetSetsDateQueryOptions = <TData = Awaited<ReturnType<typeof getSetsDate>>, TError = unknown>(date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSetsDate>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSetsDateQueryKey(date);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSetsDate>>> = ({ signal }) => getSetsDate(date, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(date), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSetsDate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSetsDateQueryResult = NonNullable<Awaited<ReturnType<typeof getSetsDate>>>
export type GetSetsDateQueryError = unknown


export function useGetSetsDate<TData = Awaited<ReturnType<typeof getSetsDate>>, TError = unknown>(
 date: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSetsDate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSetsDate>>,
          TError,
          Awaited<ReturnType<typeof getSetsDate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSetsDate<TData = Awaited<ReturnType<typeof getSetsDate>>, TError = unknown>(
 date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSetsDate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSetsDate>>,
          TError,
          Awaited<ReturnType<typeof getSetsDate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSetsDate<TData = Awaited<ReturnType<typeof getSetsDate>>, TError = unknown>(
 date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSetsDate>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSetsDate<TData = Awaited<ReturnType<typeof getSetsDate>>, TError = unknown>(
 date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSetsDate>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSetsDateQueryOptions(date,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
